### PR TITLE
fix some bug on extends find

### LINKED ISSUE #707: 开启缓存后Find只能找到一条数据
开启缓存后,进行列表查询，只能返回一条结果,部分日志如下

```
[xorm] [debug] 2017/09/08 12:29:34.069556 [cacheFind] cache bean:motorcade[<nil>] &{{906001541641539584 1504842574 1504842574} ZTY141 杭州文豪车队 杭州文豪 文豪 12345678908 1 1503641400 1503641400 0} [0xc4202d8c60 <nil>]
[xorm] [debug] 2017/09/08 12:29:34.069647 [cacheFind] cache bean:motorcade[<nil>] &{{906009062062166016 1504844367 1504844367} ZTY143 杭州文豪车队 杭州文豪 文豪 12345678908 1 1503641400 1503641400 0} [0xc4202d8ce8 <nil>]
[xorm] [warn]  2017/09/08 12:29:34.069700 [cacheFind] cache no hit:motorcade[906009062062166016] [0xc4202d8ce8 <nil>]
```

### PR DESCRIPTION
**Pull request by lunny**
will fix #707

### CODE REVIEW

File: engine.go [hunk 1]
```diff
@@ -1091,7 +1091,25 @@ func (engine *Engine) idOfV(rv reflect.Value) (core.PK, error) {
...
+			v = v.FieldByName(parts[0])
+			if v.Kind() == reflect.Ptr {
+				v = v.Elem()
+			}
+			if v.Kind() != reflect.Struct {
+				return nil, ErrUnSupportedType
+			}
+			fieldName = parts[1]
+		}
+		fmt.Println(table.Name, fieldName, v)
```
Comment (mymtw) [inline engine.go]: maybe delete this line?

Comment (lunny) [reply engine.go]: Fixed by 9680df54457a335d5ea5167e883874f5d943254d
